import { Tool, SupportLevel } from '../types';

// Helper: create modelSupport from full keys and optional partial keys
const m = (full: string[], partial: string[] = []): Record<string, SupportLevel> => ({
  ...Object.fromEntries(full.map(k => [k, 'full' as const])),
  ...Object.fromEntries(partial.map(k => [k, 'partial' as const])),
});

export const tools: Tool[] = [
  // ─── MTA TOOLS ───
  {
    name: 'Improvado',
    url: 'https://improvado.io',
    category: 'mta',
    subcategory: 'Full-Spectrum MTA',
    founded: '2017',
    hq: 'San Francisco, CA',
    audienceTags: ['Enterprise', 'Performance Marketing', 'Multi-National'],
    models: ['Custom Analytics', 'Cross-Channel Reporting', 'AI-Powered Insights'],
    modelSupport: m(['data-driven', 'custom-algo']),
    priceTier: '$$$$',
    priceLabel: 'Custom (Enterprise)',
    priceUSD: null,
    strengths: [
      '500+ pre-built data source connectors',
      'AI Agents automate 99.5% of analytics routines',
      'Enterprise-grade security (SOC2, HIPAA, GDPR, CCPA)',
      'End-to-end data pipeline from extraction to insight',
    ],
    bestFor: 'Enterprise marketing teams needing centralized data from 500+ sources with AI-powered insights',
    hasIncrementality: false,
    offersMTA: true,
    offersMMM: false,
  },
  {
    name: 'HockeyStack',
    url: 'https://hockeystack.com',
    category: 'mta',
    subcategory: 'Full-Spectrum MTA',
    founded: '2022',
    hq: 'San Francisco, CA',
    audienceTags: ['B2B / Lead Gen', 'Enterprise', 'SaaS'],
    models: [
      'First Touch',
      'Last Touch',
      'Linear',
      'Time Decay',
      'Position-Based',
      'Data-Driven',
      'Custom',
      'Account-Level',
      'Full Path',
    ],
    modelSupport: m(['first-touch', 'last-touch', 'linear', 'time-decay', 'position', 'data-driven', 'custom-algo', 'account-level', 'full-path']),
    priceTier: '$$$$',
    priceLabel: 'Custom (Enterprise)',
    priceUSD: null,
    strengths: [
      '9 attribution models with AI-powered Odin analyst',
      'GTM AI agents for sales and marketing automation',
      'Blueprints reveal ideal engagement patterns for deals',
      'Account scoring with cookieless tracking',
    ],
    bestFor: 'Enterprise B2B companies needing unified GTM intelligence with attribution and AI-powered agents',
    hasIncrementality: false,
    offersMTA: true,
    offersMMM: false,
  },
  {
    name: 'Dreamdata',
    url: 'https://dreamdata.io',
    category: 'mta',
    subcategory: 'Full-Spectrum MTA',
    founded: '2019',
    hq: 'Copenhagen, Denmark',
    audienceTags: ['B2B / Lead Gen', 'SaaS', 'Enterprise'],
    models: [
      'First Touch',
      'Last Touch',
      'Linear',
      'Time Decay',
      'Position-Based',
      'Data-Driven',
      'Custom',
    ],
    modelSupport: m(['first-touch', 'last-touch', 'linear', 'time-decay', 'position', 'data-driven', 'custom-algo']),
    priceTier: '$$',
    priceLabel: 'Free + Custom ($5K-$20K/yr typical)',
    priceUSD: null,
    strengths: [
      '#1 B2B Attribution vendor on G2',
      'Free plan with B2B web analytics and audience builder',
      'AI-powered attribution with custom models',
      'Audience Hub syncs precise audiences to ad platforms',
    ],
    bestFor: 'B2B marketers who need attribution, audience activation, and conversion syncs',
    hasIncrementality: false,
    offersMTA: true,
    offersMMM: false,
  },
  {
    name: 'Bizible (Marketo Measure)',
    url: 'https://business.adobe.com/products/marketo/marketo-measure.html',
    category: 'mta',
    subcategory: 'Full-Spectrum MTA',
    founded: '2011',
    hq: 'San Jose, CA (Adobe)',
    audienceTags: ['B2B / Lead Gen', 'Enterprise', 'Adobe Ecosystem'],
    models: [
      'First Touch',
      'Last Touch',
      'Linear',
      'Position-Based',
      'Full Path',
      'Custom',
      'Data-Driven',
    ],
    modelSupport: m(['first-touch', 'last-touch', 'linear', 'position', 'full-path', 'custom-algo', 'data-driven']),
    priceTier: '$$$$',
    priceLabel: 'Custom (Part of Adobe Marketo)',
    priceUSD: null,
    strengths: [
      'Every-touch data aggregation (not just campaign-associated)',
      'Attribution AI for sophisticated modeling',
      'Deep integration with Adobe/Marketo ecosystem',
      'Enterprise-wide reporting and data sharing',
    ],
    bestFor: 'Enterprise B2B organizations in the Adobe/Marketo ecosystem needing every-touch attribution',
    hasIncrementality: false,
    offersMTA: true,
    offersMMM: false,
  },
  {
    name: 'Ruler Analytics',
    url: 'https://www.ruleranalytics.com',
    category: 'mta',
    subcategory: 'Full-Spectrum MTA',
    founded: '2016',
    hq: 'Liverpool, UK',
    audienceTags: ['B2B / Lead Gen', 'SMB', 'Performance Marketing'],
    models: ['First Touch', 'Last Touch', 'Linear'],
    modelSupport: m(['first-touch', 'last-touch'], ['linear']),
    priceTier: '$$',
    priceLabel: '£179-£999/mo (~$2.7K-$15K/yr)',
    priceUSD: 8900,
    strengths: [
      'Integrated call tracking + marketing attribution',
      'Revenue attribution connecting leads to CRM sales',
      'Supports form, call, and live chat attribution',
      '1,000+ app integrations',
    ],
    bestFor: 'B2B lead gen businesses needing to connect marketing touchpoints to CRM revenue data',
    hasIncrementality: false,
    offersMTA: true,
    offersMMM: false,
  },
  {
    name: 'Attribution (LeadsRx)',
    url: 'https://leadsrx.com',
    category: 'mta',
    subcategory: 'Full-Spectrum MTA',
    founded: '2015',
    hq: 'Portland, OR',
    audienceTags: ['B2B / Lead Gen', 'E-commerce / DTC', 'Performance Marketing', 'Privacy-First'],
    models: [
      'First Touch',
      'Last Touch',
      'Linear',
      'Time Decay',
      'Position-Based',
      'Custom',
    ],
    modelSupport: m(['first-touch', 'last-touch', 'linear', 'time-decay', 'position', 'custom-algo']),
    priceTier: '$$$',
    priceLabel: 'Custom (Contact Sales)',
    priceUSD: null,
    strengths: [
      'Omni-channel attribution including broadcast radio, CTV/OTT, streaming',
      'Universal Pixel captures 100% of inbound digital traffic',
      'Privacy Studio with data clean room capabilities',
      'Customer journey analytics with cross-device unification',
    ],
    bestFor: 'Enterprise marketers needing impartial cross-channel attribution spanning digital and broadcast channels',
    hasIncrementality: false,
    offersMTA: true,
    offersMMM: false,
  },
  {
    name: 'Cometly',
    url: 'https://cometly.com',
    category: 'mta',
    subcategory: 'Full-Spectrum MTA',
    founded: '2021',
    hq: 'Austin, TX',
    audienceTags: ['E-commerce / DTC', 'SaaS', 'Performance Marketing', 'B2B / Lead Gen'],
    models: [
      'First Touch',
      'Last Touch',
      'Linear',
      'Time Decay',
      'Position-Based',
      'Data-Driven',
    ],
    modelSupport: m(['first-touch', 'last-touch', 'linear', 'time-decay', 'position', 'data-driven']),
    priceTier: '$$',
    priceLabel: 'Custom (Contact Sales)',
    priceUSD: null,
    strengths: [
      'AI Ads Manager for campaign optimization',
      'Server-side tracking with Conversion API',
      'Multi-touch attribution with full funnel tracking',
      'AI Chat to analyze and act on data instantly',
    ],
    bestFor: 'Growth and marketing teams at SaaS and DTC companies needing accurate MTA with AI-powered optimization',
    hasIncrementality: false,
    offersMTA: true,
    offersMMM: false,
  },
  {
    name: 'Usermaven',
    url: 'https://usermaven.com',
    category: 'mta',
    subcategory: 'Full-Spectrum MTA',
    founded: '2021',
    hq: 'Unknown',
    audienceTags: ['SaaS', 'SMB', 'E-commerce / DTC', 'Privacy-First'],
    models: [
      'First Touch',
      'Last Touch',
      'Linear',
      'Time Decay',
      'Position-Based',
      'Data-Driven',
      'Custom',
    ],
    modelSupport: m(['first-touch', 'last-touch', 'linear', 'time-decay', 'position', 'data-driven', 'custom-algo']),
    priceTier: '$',
    priceLabel: '$71-$169/mo ($852-$2K/yr)',
    priceUSD: 2028,
    strengths: [
      '7 AI-powered attribution models with cookieless tracking',
      'Combined web analytics + product analytics + attribution',
      'Ad-blocker bypassing captures 99% of data',
      'GDPR/CCPA compliant with EU hosting and cookie-less option',
    ],
    bestFor: 'SaaS and SMB teams wanting affordable, privacy-first web analytics + attribution in one tool',
    hasIncrementality: false,
    offersMTA: true,
    offersMMM: false,
  },
  {
    name: 'ThoughtMetric',
    url: 'https://thoughtmetric.io',
    category: 'mta',
    subcategory: 'Full-Spectrum MTA',
    founded: '2020',
    hq: 'Toronto, Canada',
    audienceTags: ['E-commerce / DTC', 'SMB', 'Shopify'],
    models: ['First Touch', 'Last Touch', 'Linear', 'Time Decay', 'Position-Based'],
    modelSupport: m(['first-touch', 'last-touch', 'linear', 'time-decay', 'position']),
    priceTier: '$',
    priceLabel: '$99/mo (~$1.2K/yr)',
    priceUSD: 1188,
    strengths: [
      'Simple one-plan pricing with all features included',
      '5 attribution models with real-time 10-minute refresh',
      'Server-side tagging and Conversion API',
      'AI connectors (Claude + ChatGPT) for analysis',
    ],
    bestFor: 'Small to mid-size e-commerce stores needing affordable multi-touch attribution',
    hasIncrementality: false,
    offersMTA: true,
    offersMMM: false,
  },
  {
    name: 'Wicked Reports',
    url: 'https://wickedreports.com',
    category: 'mta',
    subcategory: 'Full-Spectrum MTA',
    founded: '2015',
    hq: 'Unknown',
    audienceTags: ['E-commerce / DTC', 'Performance Marketing'],
    models: ['First Touch', 'Last Touch', 'Linear', 'Full Path', 'Custom'],
    modelSupport: m(['first-touch', 'last-touch', 'linear', 'full-path', 'custom-algo']),
    priceTier: '$$',
    priceLabel: '$499-$999/mo ($6K-$12K/yr)',
    priceUSD: 8388,
    strengths: [
      'New vs repeat customer attribution reduces nCAC',
      'Advanced Signal trains Meta to find first-time buyers',
      '5 Forces AI provides weekly Scale/Chill/Kill recommendations',
      'Lifetime lookback with eternal server-side tracking',
    ],
    bestFor: 'E-commerce brands ($5M-$50M revenue) needing new vs repeat customer attribution',
    hasIncrementality: false,
    offersMTA: true,
    offersMMM: false,
  },
  {
    name: 'CaliberMind',
    url: 'https://calibermind.com',
    category: 'mta',
    subcategory: 'Full-Spectrum MTA',
    founded: '2017',
    hq: 'Boulder, CO',
    audienceTags: ['B2B / Lead Gen', 'Enterprise'],
    models: [
      'First Touch',
      'Last Touch',
      'Linear',
      'Time Decay',
      'Position-Based',
      'Full Path',
      'Custom',
      'Account-Level',
    ],
    modelSupport: m(['first-touch', 'last-touch', 'linear', 'time-decay', 'position', 'full-path', 'custom-algo', 'account-level']),
    priceTier: '$$$',
    priceLabel: 'Custom (Enterprise)',
    priceUSD: null,
    strengths: [
      'Chain-based attribution designed for complex B2B buying journeys',
      'Composable CDP with full data transparency and ownership',
      '170+ pre-built connectors with flexible enterprise data architecture',
      'ABM insights with account scoring and buyer journey intelligence',
    ],
    bestFor: 'Enterprise B2B marketing teams needing customizable multi-touch attribution with ABM capabilities',
    hasIncrementality: false,
    offersMTA: true,
    offersMMM: false,
  },
  {
    name: 'Adobe Analytics (Attribution IQ)',
    url: 'https://business.adobe.com/products/adobe-analytics.html',
    category: 'mta',
    subcategory: 'Enterprise / Legacy MTA',
    founded: '1996',
    hq: 'San Jose, CA',
    audienceTags: ['Enterprise', 'Adobe Ecosystem', 'B2B / Lead Gen', 'E-commerce / DTC'],
    models: [
      'First Touch',
      'Last Touch',
      'Linear',
      'Time Decay',
      'Position-Based',
      'Custom',
      'Data-Driven',
      'Account-Level (B2B Edition)',
    ],
    modelSupport: m(['first-touch', 'last-touch', 'linear', 'time-decay', 'position', 'custom-algo', 'data-driven', 'account-level']),
    priceTier: '$$$$',
    priceLabel: 'Custom (~$100K+/yr)',
    priceUSD: null,
    strengths: [
      'Full Adobe Experience Cloud integration with unified customer data',
      'Cross-channel journey analytics connecting online and offline data',
      'B2B Edition with account-level and buying-group analysis',
      'AI-powered content analytics and predictive capabilities',
    ],
    bestFor: 'Enterprise organizations in the Adobe ecosystem needing cross-channel journey analytics and flexible attribution',
    hasIncrementality: false,
    offersMTA: true,
    offersMMM: false,
  },
  {
    name: 'Google Analytics 4',
    url: 'https://marketingplatform.google.com/about/analytics/',
    category: 'mta',
    subcategory: 'Enterprise / Legacy MTA',
    founded: '2020',
    hq: 'Mountain View, CA',
    audienceTags: ['SMB', 'E-commerce / DTC', 'Performance Marketing', 'Enterprise'],
    models: [
      'Data-Driven',
      'Last Touch',
      'First Touch',
      'Linear',
      'Time Decay',
      'Position-Based',
    ],
    modelSupport: m(['first-touch', 'last-touch', 'linear', 'time-decay', 'position', 'data-driven']),
    priceTier: 'Free',
    priceLabel: 'Free (GA4) / ~$50K-$150K/yr (Analytics 360)',
    priceUSD: 0,
    strengths: [
      'Free tier with robust cross-platform attribution and data-driven modeling',
      'Deep integration with Google Ads, DV360, SA360, and BigQuery',
      'Machine learning-powered predictive audiences and insights',
      'Cross-device and cross-platform measurement built-in',
    ],
    bestFor: 'Businesses of all sizes needing free or enterprise-grade analytics with data-driven attribution',
    hasIncrementality: false,
    offersMTA: true,
    offersMMM: false,
  },
  {
    name: 'Growify',
    url: 'https://growify.ai',
    category: 'mta',
    subcategory: 'Specialized / Niche MTA',
    founded: '2021',
    hq: 'Unknown',
    audienceTags: ['E-commerce / DTC', 'Shopify', 'SMB', 'Performance Marketing'],
    models: ['First Touch', 'Last Touch', 'Linear', 'Multi-Touch', 'Data-Driven'],
    modelSupport: m(['first-touch', 'last-touch', 'linear', 'data-driven'], ['custom-algo']),
    priceTier: '$',
    priceLabel: '$249-$799/mo ($2,988-$9,588/yr)',
    priceUSD: 4788,
    strengths: [
      'AI-powered omnichannel attribution with server-side pixel tracking',
      'Affordable pricing designed for e-commerce/DTC brands',
      'Creative analytics with cross-channel performance tracking',
      'Budget allocation and pacing across all marketing channels',
    ],
    bestFor: 'E-commerce and DTC brands needing affordable multi-touch attribution with creative analytics',
    hasIncrementality: false,
    offersMTA: true,
    offersMMM: false,
  },
  {
    name: 'Matomo',
    url: 'https://matomo.org',
    category: 'mta',
    subcategory: 'Specialized / Niche MTA',
    founded: '2007',
    hq: 'Wellington, New Zealand',
    audienceTags: ['Privacy-First', 'SMB', 'Enterprise', 'E-commerce / DTC'],
    models: [
      'Last Touch',
      'First Touch',
      'Linear',
      'Multi-Channel Conversion Attribution',
    ],
    modelSupport: m(['first-touch', 'last-touch', 'linear'], ['position']),
    priceTier: 'Free',
    priceLabel: 'Free (On-Premise) / €22-€220+/mo Cloud',
    priceUSD: 0,
    strengths: [
      '100% data ownership with GDPR/CCPA compliance',
      'Free open-source self-hosted option with unlimited data',
      'Multi-Channel Conversion Attribution plugin for advanced models',
      'No data sampling, 100% accurate reporting',
    ],
    bestFor: 'Privacy-conscious organizations needing GDPR-compliant web analytics with full data ownership',
    hasIncrementality: false,
    offersMTA: true,
    offersMMM: false,
  },
  {
    name: 'AppsFlyer',
    url: 'https://www.appsflyer.com',
    category: 'mta',
    subcategory: 'Specialized / Niche MTA',
    founded: '2011',
    hq: 'Herzliya, Israel',
    audienceTags: ['Mobile', 'E-commerce / DTC', 'Enterprise', 'Performance Marketing'],
    models: [
      'Last Touch',
      'Multi-Touch',
      'Data-Driven',
      'SKAN Attribution',
      'CTV/OTT',
    ],
    modelSupport: m(['first-touch', 'last-touch', 'data-driven'], ['custom-algo']),
    priceTier: '$$',
    priceLabel: 'Free (Zero) / $0.07/conversion (Growth) / Custom (Enterprise)',
    priceUSD: null,
    strengths: [
      'Industry #1 mobile measurement partner trusted by 15,000+ brands',
      'Comprehensive SKAN/iOS 14+ solutions with conversion modeling',
      'Advanced fraud protection (Protect360) with behavioral biometrics',
      'Cross-platform measurement: mobile, web, CTV, PC & console',
    ],
    bestFor: 'Mobile-first brands needing best-in-class mobile attribution, SKAN support, and fraud protection',
    hasIncrementality: false,
    offersMTA: true,
    offersMMM: false,
  },
  {
    name: 'Branch',
    url: 'https://www.branch.io',
    category: 'mta',
    subcategory: 'Specialized / Niche MTA',
    founded: '2014',
    hq: 'Palo Alto, CA',
    audienceTags: ['Mobile', 'E-commerce / DTC', 'Enterprise', 'Performance Marketing'],
    models: ['Last Touch', 'Multi-Touch', 'Cross-Platform', 'CTV/OTT Attribution'],
    modelSupport: m(['first-touch', 'last-touch'], ['data-driven']),
    priceTier: '$$',
    priceLabel: 'Free trial (Basics) / Custom (Essentials/Enterprise)',
    priceUSD: null,
    strengths: [
      'Industry-leading deep linking handling 6,000+ edge cases',
      'Trusted by 100,000+ brands with 3.5B user network',
      'Comprehensive mobile + web + CTV/OTT measurement',
      'AI-powered Ivy tool for personalized marketing recommendations',
    ],
    bestFor: 'Mobile-first brands needing seamless deep linking combined with mobile measurement',
    hasIncrementality: false,
    offersMTA: true,
    offersMMM: false,
  },
  {
    name: 'Adjust',
    url: 'https://www.adjust.com',
    category: 'mta',
    subcategory: 'Specialized / Niche MTA',
    founded: '2012',
    hq: 'Berlin, Germany',
    audienceTags: ['Mobile', 'Enterprise', 'Performance Marketing', 'E-commerce / DTC'],
    models: [
      'Last Touch',
      'First Touch',
      'Multi-Touch',
      'SKAN Attribution',
      'CTV/OTT',
      'Incrementality',
    ],
    modelSupport: m(['first-touch', 'last-touch'], ['data-driven', 'custom-algo']),
    priceTier: '$$',
    priceLabel: 'Free (Base, 1,500/mo) / Custom (Core/Enterprise)',
    priceUSD: null,
    strengths: [
      'Free tier with up to 1,500 monthly attributions for small developers',
      'Comprehensive iOS 14+/SKAN solutions included at no extra cost',
      'Part of AppLovin ecosystem providing integrated ad tech stack',
      'InSight incrementality measurement and fraud prevention suite',
    ],
    bestFor: 'Mobile app developers and marketers needing scalable attribution with iOS/SKAN support',
    hasIncrementality: true,
    offersMTA: true,
    offersMMM: false,
  },
  {
    name: 'Singular',
    url: 'https://www.singular.net',
    category: 'mta',
    subcategory: 'Specialized / Niche MTA',
    founded: '2014',
    hq: 'Tel Aviv, Israel',
    audienceTags: ['Mobile', 'Performance Marketing', 'SMB', 'Enterprise'],
    models: [
      'Last Touch',
      'First Touch',
      'Multi-Touch',
      'SKAN Attribution',
      'Cross-Device',
    ],
    modelSupport: m(['first-touch', 'last-touch'], ['data-driven', 'custom-algo']),
    priceTier: '$',
    priceLabel: 'Free (15K conversions) / $0.05/conversion (Growth) / Custom (Enterprise)',
    priceUSD: null,
    strengths: [
      'Unified cost aggregation + attribution in one platform (True ROI)',
      'Free tier with 15K conversions including fraud prevention and creative reporting',
      'No-code ETL and reverse-ETL for seamless data warehouse integration',
      'AI-powered insights with transparent per-conversion pricing',
    ],
    bestFor: 'Growth-focused mobile app marketers needing unified cost + attribution analytics',
    hasIncrementality: false,
    offersMTA: true,
    offersMMM: false,
  },

  // ─── MMM TOOLS ───
  {
    name: 'Google Meridian',
    url: 'https://developers.google.com/meridian',
    category: 'mmm',
    subcategory: 'Open-Source Framework',
    founded: '2024',
    hq: 'Mountain View, CA',
    audienceTags: ['Data Science Team', 'Enterprise', 'Performance Marketing'],
    models: ['Bayesian MMM', 'Geo-level modeling', 'Scenario Planning'],
    modelSupport: m(['bayesian', 'scenario', 'geolift']),
    priceTier: 'Free',
    priceLabel: 'Free / Open Source',
    priceUSD: 0,
    strengths: [
      'Open-source Bayesian MMM built by Google with strong statistical foundation',
      'Geo-level modeling for more granular media impact measurement',
      'Integrates with Google ad stack for richer data inputs',
      'Revenue and ROI optimization with scenario planning',
    ],
    bestFor: 'Data science teams wanting a robust open-source Bayesian MMM with geo-level granularity',
    hasIncrementality: true,
    offersMTA: false,
    offersMMM: true,
  },
  {
    name: 'Meta Robyn',
    url: 'https://facebookexperimental.github.io/Robyn/',
    category: 'mmm',
    subcategory: 'Open-Source Framework',
    founded: '2021',
    hq: 'Menlo Park, CA',
    audienceTags: ['Data Science Team', 'Performance Marketing', 'E-commerce / DTC'],
    models: [
      'Ridge Regression MMM',
      'Nevergrad Optimization',
      'Calibration with Experiments',
    ],
    modelSupport: m(['econometric', 'ai-ml', 'scenario'], ['bayesian']),
    priceTier: 'Free',
    priceLabel: 'Free / Open Source',
    priceUSD: 0,
    strengths: [
      'Open-source MMM from Meta with automated hyperparameter tuning via Nevergrad',
      'Built-in calibration with experimental results (lift studies)',
      'Budget allocator with diminishing returns modeling',
      'Available in both R and Python with active community',
    ],
    bestFor: 'Data science teams wanting a well-documented open-source MMM with experimental calibration',
    hasIncrementality: false,
    offersMTA: false,
    offersMMM: true,
  },
  {
    name: 'PyMC-Marketing',
    url: 'https://www.pymc-marketing.io',
    category: 'mmm',
    subcategory: 'Open-Source Framework',
    founded: '2022',
    hq: 'Unknown',
    audienceTags: ['Data Science Team', 'Enterprise', 'E-commerce / DTC'],
    models: ['Bayesian MMM', 'Customer Lifetime Value', 'Attribution'],
    modelSupport: m(['bayesian', 'scenario']),
    priceTier: 'Free',
    priceLabel: 'Free / Open Source (paid consulting available)',
    priceUSD: 0,
    strengths: [
      'Full Bayesian MMM with uncertainty quantification via PyMC probabilistic programming',
      'Includes CLV models alongside MMM for holistic marketing analytics',
      'Highly customizable with full access to underlying probabilistic model',
      'Backed by PyMC Labs with professional consulting and support available',
    ],
    bestFor: 'Data science teams wanting maximum flexibility in Bayesian MMM with full probabilistic modeling',
    hasIncrementality: false,
    offersMTA: false,
    offersMMM: true,
  },
  {
    name: 'LightweightMMM (Google)',
    url: 'https://github.com/google/lightweight_mmm',
    category: 'mmm',
    subcategory: 'Open-Source Framework',
    founded: '2022',
    hq: 'Mountain View, CA',
    audienceTags: ['Data Science Team'],
    models: ['Bayesian MMM'],
    modelSupport: m(['bayesian'], ['scenario']),
    priceTier: 'Free',
    priceLabel: 'Free / Open Source (ARCHIVED — Use Meridian instead)',
    priceUSD: 0,
    strengths: [
      'Simple, lightweight Bayesian MMM implementation',
      'Good for learning MMM fundamentals',
      'Built on JAX/NumPyro for fast inference',
    ],
    bestFor: 'DEPRECATED — Users should migrate to Google Meridian. Only useful for existing implementations or learning.',
    hasIncrementality: false,
    offersMTA: false,
    offersMMM: true,
    deprecated: true,
  },
  {
    name: 'Keen Decision Systems',
    url: 'https://keends.com',
    category: 'mmm',
    subcategory: 'Modern SaaS',
    founded: '2012',
    hq: 'Cary, NC',
    audienceTags: ['E-commerce / DTC', 'CPG / Retail', 'Performance Marketing', 'SMB'],
    models: ['Bayesian MMM', 'Adaptive AI Models', 'Scenario Planning'],
    modelSupport: m(['bayesian', 'ai-ml', 'scenario']),
    priceTier: '$$',
    priceLabel: 'Custom (likely $10K-$20K/yr for SMB tiers)',
    priceUSD: null,
    strengths: [
      'Adaptive Bayesian MMM that updates weekly with new data',
      'Built-in scenario planning and budget optimization',
      'Fast setup — claims optimized marketing plan in 5 minutes',
      'Free tier available for initial marketing mix plan',
    ],
    bestFor: 'Mid-market brands and agencies wanting an always-on, self-service MMM platform',
    hasIncrementality: false,
    offersMTA: false,
    offersMMM: true,
  },
  {
    name: 'Recast',
    url: 'https://getrecast.com',
    category: 'mmm',
    subcategory: 'Modern SaaS',
    founded: '2021',
    hq: 'New York, NY',
    audienceTags: ['E-commerce / DTC', 'Performance Marketing', 'SMB'],
    models: ['Bayesian MMM', 'Scenario Planning', 'Budget Optimization'],
    modelSupport: m(['bayesian', 'scenario']),
    priceTier: '$$',
    priceLabel: 'Custom pricing',
    priceUSD: null,
    strengths: [
      'Modern Bayesian MMM built specifically for DTC and omnichannel brands',
      'Strong emphasis on model validation and statistical rigor',
      'Real-time measurement and continuous model updates',
      'Transparent methodology with strong educational content',
    ],
    bestFor: 'Modern DTC and omnichannel brands wanting rigorous, Bayesian MMM with transparent methodology',
    hasIncrementality: false,
    offersMTA: false,
    offersMMM: true,
  },
  {
    name: 'Sellforte',
    url: 'https://sellforte.com',
    category: 'mmm',
    subcategory: 'Modern SaaS',
    founded: '2017',
    hq: 'Helsinki, Finland',
    audienceTags: ['E-commerce / DTC', 'CPG / Retail', 'Performance Marketing', 'Enterprise'],
    models: [
      'Causal MMM',
      'Incrementality Testing',
      'Budget Optimization',
      'Scenario Planning',
    ],
    modelSupport: m(['bayesian', 'econometric', 'scenario', 'geolift']),
    priceTier: '$$$',
    priceLabel: '$4,390-$7,990/mo ($52K-$96K/yr)',
    priceUSD: 52680,
    strengths: [
      'Transparent pricing with clear tier structure (Essentials/Growth/Advanced)',
      'Campaign and ad-set level granularity with daily digital updates',
      'Built-in geo-lift testing and incrementality calibration',
      'Extensive integrations: Shopify, BigCommerce, Magento, 20+ ad platforms',
    ],
    bestFor: 'E-commerce and DTC brands wanting full-featured MMM SaaS with transparent pricing',
    hasIncrementality: true,
    offersMTA: false,
    offersMMM: true,
  },
  {
    name: 'Prescient AI',
    url: 'https://www.prescientai.com',
    category: 'mmm',
    subcategory: 'Modern SaaS',
    founded: '2021',
    hq: 'New York, NY',
    audienceTags: ['E-commerce / DTC', 'Performance Marketing', 'Shopify'],
    models: ['AI-powered MMM', 'Cross-channel Attribution', 'Scenario Planning'],
    modelSupport: m(['ai-ml', 'scenario']),
    priceTier: '$$',
    priceLabel: 'Custom pricing',
    priceUSD: null,
    strengths: [
      'AI-powered MMM tailored for omnichannel DTC brands',
      'Cross-channel revenue attribution including Amazon performance',
      'Claims 20%+ lift in ROAS for customers',
      'Integrates with major ad platforms and e-commerce systems',
    ],
    bestFor: 'DTC and omnichannel e-commerce brands wanting AI-driven MMM with Amazon attribution',
    hasIncrementality: false,
    offersMTA: false,
    offersMMM: true,
  },
  {
    name: 'Arima',
    url: 'https://arimadata.com',
    category: 'mmm',
    subcategory: 'Modern SaaS',
    founded: 'Unknown',
    hq: 'Canada',
    audienceTags: ['Enterprise', 'CPG / Retail', 'Multi-National', 'B2B / Lead Gen'],
    models: [
      'Marketing Mix Modeling',
      'Cross-Media Planning',
      'Persona Building',
      'Location Intelligence',
    ],
    modelSupport: m(['bayesian', 'ai-ml', 'scenario']),
    priceTier: '$$',
    priceLabel: 'Custom pricing',
    priceUSD: null,
    strengths: [
      'Full marketing intelligence suite beyond just MMM (Persona Builder, Cross-Media Planner, Location Intelligence)',
      'Strong enterprise client base (Coca-Cola, Bayer, Danone, Unilever, Subway, Deloitte)',
      'Location intelligence with foot traffic and geo-targeted decision making',
      'Synthetic data and InstaPoll for rapid consumer insights',
    ],
    bestFor: 'Enterprise brands wanting a comprehensive marketing intelligence platform combining MMM with audience insights',
    hasIncrementality: false,
    offersMTA: false,
    offersMMM: true,
  },
  {
    name: 'Cassandra',
    url: 'https://cassandra.app',
    category: 'mmm',
    subcategory: 'Modern SaaS',
    founded: '2022',
    hq: 'Italy',
    audienceTags: ['E-commerce / DTC', 'SMB', 'B2B / Lead Gen', 'Performance Marketing'],
    models: [
      'Bayesian MMM',
      'Geo-Incrementality Testing',
      'Scenario Planning',
      'Budget Optimization',
    ],
    modelSupport: m(['bayesian', 'scenario', 'geolift']),
    priceTier: '$$',
    priceLabel: '€1,500-€2,400/mo (~$19K-$31K/yr)',
    priceUSD: 25200,
    strengths: [
      'Combined MMM + incrementality testing in one platform with calibration',
      'Transparent pricing starting at €1,500/mo for geo-experiments only',
      'Monthly model refreshes with continuous validation',
      'Serves diverse industries: ecommerce, B2B, education, fintech, charity',
    ],
    bestFor: 'SMBs and mid-market brands wanting affordable, self-service MMM with built-in incrementality testing',
    hasIncrementality: true,
    offersMTA: false,
    offersMMM: true,
  },
  {
    name: 'Circana',
    url: 'https://www.circana.com',
    category: 'mmm',
    subcategory: 'Legacy / Consulting-Led',
    founded: '2023',
    hq: 'Chicago, IL',
    audienceTags: ['Enterprise', 'CPG / Retail', 'Multi-National'],
    models: [
      'Marketing Mix Modeling',
      'Market Research Analytics',
      'Pricing Optimization',
    ],
    modelSupport: m(['econometric', 'ai-ml', 'scenario']),
    priceTier: '$$$$',
    priceLabel: 'Custom enterprise pricing ($100K+/yr)',
    priceUSD: null,
    strengths: [
      'Massive proprietary data assets (receipt, POS, panel data) from IRI+NPD merger',
      'Deep CPG/retail expertise with unmatched category benchmarking',
      'Full-service analytics combining MMM with market research and pricing',
      'Global presence across 22+ countries',
    ],
    bestFor: 'Large CPG/retail enterprises needing MMM integrated with proprietary retail/consumer data',
    hasIncrementality: false,
    offersMTA: false,
    offersMMM: true,
  },
  {
    name: 'Analytic Partners',
    url: 'https://analyticpartners.com',
    category: 'mmm',
    subcategory: 'Legacy / Consulting-Led',
    founded: '2000',
    hq: 'New York, NY',
    audienceTags: ['Enterprise', 'Multi-National', 'CPG / Retail'],
    models: [
      'Commercial Analytics MMM',
      'Brand Impact Modeling',
      'Agile Learning/Experimentation',
      'Scenario Planning',
    ],
    modelSupport: m(['econometric', 'ai-ml', 'scenario']),
    priceTier: '$$$$',
    priceLabel: 'Custom enterprise pricing ($100K+/yr)',
    priceUSD: null,
    strengths: [
      'GPS Enterprise platform for unified commercial analytics and decision-making',
      'ROI Genome — proprietary cross-industry ROI benchmarking database',
      'Named Leader in Gartner Magic Quadrant and Forrester Wave',
      'Goes beyond MMM: pricing optimization, customer segmentation, brand impact',
    ],
    bestFor: 'Large enterprises wanting comprehensive commercial analytics combining MMM with pricing and brand impact',
    hasIncrementality: false,
    offersMTA: false,
    offersMMM: true,
  },
  {
    name: 'Ipsos MMA',
    url: 'https://mma.com',
    category: 'mmm',
    subcategory: 'Legacy / Consulting-Led',
    founded: '2000',
    hq: 'New York, NY',
    audienceTags: ['Enterprise', 'Multi-National', 'CPG / Retail'],
    models: [
      'Marketing Mix Modeling',
      'Unified Marketing Measurement',
      'Agile Attribution',
      'Pricing Analytics',
    ],
    modelSupport: m(['econometric', 'ai-ml', 'scenario']),
    priceTier: '$$$$',
    priceLabel: 'Custom enterprise pricing ($150K+/yr)',
    priceUSD: null,
    strengths: [
      'Named Leader in both Gartner Magic Quadrant AND Forrester Wave (2025-2026)',
      'Unified marketing measurement combining MMM with agile attribution',
      'Activate platform for real-time marketing planning and optimization',
      'Deep enterprise expertise with clients like Volvo, GM, Nationwide, Prudential',
    ],
    bestFor: 'Large multinational enterprises needing best-in-class unified marketing measurement',
    hasIncrementality: false,
    offersMTA: true,
    offersMMM: true,
  },
  {
    name: 'Kantar',
    url: 'https://www.kantar.com',
    category: 'mmm',
    subcategory: 'Legacy / Consulting-Led',
    founded: '1992',
    hq: 'London, UK',
    audienceTags: ['Enterprise', 'Multi-National', 'CPG / Retail'],
    models: [
      'Marketing Mix Modeling',
      'Brand Equity Measurement',
      'Creative Effectiveness',
    ],
    modelSupport: m(['econometric', 'scenario']),
    priceTier: '$$$$',
    priceLabel: 'Custom enterprise pricing ($100K+/yr)',
    priceUSD: null,
    strengths: [
      'World\'s largest brand equity study (BrandZ) with 4.3M consumers across 21K brands',
      'Blueprint for Brand Growth framework based on 6.5B consumer data points',
      'Global scale: 20,000+ employees across 90+ markets',
      'Holistic brand and marketing analytics combining MMM with brand health and creative testing',
    ],
    bestFor: 'Large multinational enterprises wanting MMM integrated with world-class brand equity research',
    hasIncrementality: false,
    offersMTA: false,
    offersMMM: true,
  },

  // ─── BOTH MTA + MMM ───
  {
    name: 'Rockerbox',
    url: 'https://www.rockerbox.com',
    category: 'both',
    founded: '2013',
    hq: 'New York, NY',
    audienceTags: ['E-commerce / DTC', 'Enterprise', 'Performance Marketing'],
    models: [
      'First Touch',
      'Last Touch',
      'Linear',
      'Custom',
      'MMM',
      'Incrementality Testing',
    ],
    modelSupport: m(['mta-suite', 'mmm-suite', 'incrementality', 'scenario']),
    priceTier: '$$$',
    priceLabel: '~$30K-$60K/yr (Starter from $200/mo, enterprise much higher)',
    priceUSD: 36000,
    strengths: [
      'All-in-one MTA + MMM + Incrementality platform with unified data foundation',
      'SOC2-certified centralized marketing data foundation',
      'Cross-methodology calibration — see where models align and diverge',
      'Acquired by DoubleVerify (March 2025) adding verification capabilities',
    ],
    bestFor: 'Enterprise and DTC brands needing unified MTA + MMM + incrementality testing',
    hasIncrementality: true,
    offersMTA: true,
    offersMMM: true,
    mtaDetail: 'Full multi-touch attribution across paid, organic, affiliate',
    mmmDetail: 'Marketing mix modeling with cross-methodology calibration',
  },
  {
    name: 'Northbeam',
    url: 'https://www.northbeam.io',
    category: 'both',
    founded: '2019',
    hq: 'Los Angeles, CA',
    audienceTags: ['E-commerce / DTC', 'Performance Marketing', 'Shopify'],
    models: [
      'First Touch',
      'Last Touch',
      'Linear',
      'Data-Driven',
      'Clicks + Deterministic Views',
      'MMM+',
    ],
    modelSupport: m(['mta-suite', 'scenario'], ['mmm-suite', 'incrementality']),
    priceTier: '$$$',
    priceLabel: 'From $1,500/mo (Starter); Custom for Pro/Enterprise',
    priceUSD: 30000,
    strengths: [
      'Industry-leading first-party multi-touch attribution with deterministic view-through',
      'Northbeam Apex — direct ad platform algorithm integration for improved delivery',
      'Creative analytics and product analytics across all channels',
      '800+ companies trust it; $34B in ad-attributed revenue tracked',
    ],
    bestFor: 'E-commerce/DTC brands spending $1M+/yr on ads needing accurate MTA with optional MMM+',
    hasIncrementality: true,
    offersMTA: true,
    offersMMM: true,
    mtaDetail: 'First-party MTA with deterministic view-through and creative analytics',
    mmmDetail: 'MMM+ available as enterprise add-on for strategic budget planning',
  },
  {
    name: 'SegmentStream',
    url: 'https://segmentstream.com',
    category: 'both',
    founded: '2019',
    hq: 'London, UK',
    audienceTags: ['B2B / Lead Gen', 'E-commerce / DTC', 'Performance Marketing', 'Privacy-First'],
    models: [
      'AI-Powered Attribution',
      'Geo-Lift Incrementality',
      'MMM/Budget Optimization',
      'Synthetic Conversions',
    ],
    modelSupport: m(['mta-suite', 'mmm-suite', 'incrementality', 'scenario']),
    priceTier: '$$$$',
    priceLabel: 'From $5,000/mo (~$60K+/yr)',
    priceUSD: 60000,
    strengths: [
      'AI-powered synthetic conversions that enhance ad platform performance in cookieless world',
      'Predictive lead scoring and customer LTV prediction for B2B and DTC',
      'Managed service model with strategic consulting and monthly performance reviews',
      'Works for both B2B lead gen (predictive scoring) and DTC (attribution + budget optimization)',
    ],
    bestFor: 'Performance marketing teams (B2B or DTC) spending $50K+/mo on ads needing AI-powered attribution with expert support',
    hasIncrementality: true,
    offersMTA: true,
    offersMMM: true,
    mtaDetail: 'AI-powered attribution with synthetic conversions and predictive scoring',
    mmmDetail: 'MMM/Budget Optimization with geo-lift incrementality',
  },
  {
    name: 'Lifesight',
    url: 'https://lifesight.io',
    category: 'both',
    founded: '2018',
    hq: 'Singapore',
    audienceTags: ['E-commerce / DTC', 'CPG / Retail', 'Enterprise', 'Privacy-First'],
    models: [
      'Causal MMM',
      'Incrementality-Adjusted Attribution',
      'Geo-Based Incrementality Testing',
    ],
    modelSupport: m(['mta-suite', 'mmm-suite', 'incrementality', 'scenario']),
    priceTier: '$$$',
    priceLabel: 'Custom annual subscription',
    priceUSD: null,
    strengths: [
      'Unified Measurement OS combining Causal MMM + Incrementality Testing + Attribution',
      'Causal discovery and validation — goes beyond correlation to true causality',
      'CTV integration (Roku partnership) for connected TV measurement',
      'No-code setup with fast time-to-value and free guided onboarding',
    ],
    bestFor: 'Mid-market to enterprise brands needing unified causal measurement with attribution, MMM, and incrementality',
    hasIncrementality: true,
    offersMTA: true,
    offersMMM: true,
    mtaDetail: 'Incrementality-adjusted attribution (causal approach)',
    mmmDetail: 'Causal MMM with scenario planning and geo-based testing',
  },
  {
    name: 'Adobe Mix Modeler',
    url: 'https://business.adobe.com/products/mix-modeler.html',
    category: 'both',
    founded: '2023',
    hq: 'San Jose, CA',
    audienceTags: ['Enterprise', 'Adobe Ecosystem', 'Multi-National', 'CPG / Retail'],
    models: [
      'Unified MMM + MTA',
      'AI/ML Incrementality Scoring',
      'Scenario Planning',
    ],
    modelSupport: m(['mta-suite', 'mmm-suite', 'incrementality', 'scenario']),
    priceTier: '$$$$',
    priceLabel: 'Custom enterprise (part of Adobe Experience Platform)',
    priceUSD: null,
    strengths: [
      'Proprietary AI/ML that combines MMM and MTA into one holistic measurement approach',
      'Deep integration with Adobe Experience Platform ecosystem',
      'Marketing scenario planning with AI-powered budget optimization',
      'Data governance tools with transparency in model quality and results',
    ],
    bestFor: 'Large enterprise organizations in the Adobe ecosystem needing unified MMM + MTA with scenario planning',
    hasIncrementality: true,
    offersMTA: true,
    offersMMM: true,
    mtaDetail: 'Multi-touch attribution on Adobe Experience Platform',
    mmmDetail: 'MMM with AI/ML incrementality scoring on AEP',
  },
  {
    name: 'Triple Whale',
    url: 'https://www.triplewhale.com',
    category: 'both',
    founded: '2021',
    hq: 'Columbus, OH',
    audienceTags: ['E-commerce / DTC', 'Shopify', 'SMB', 'Performance Marketing'],
    models: [
      'Total Impact',
      'First Click',
      'Last Click',
      'Linear All',
      'Linear Paid',
      'Triple Attribution',
      'Triple Attribution + Views',
      'MMM',
    ],
    modelSupport: m(['mta-suite', 'mmm-suite', 'scenario'], ['incrementality']),
    priceTier: '$$',
    priceLabel: 'Free to $1,290+/mo (scales with GMV)',
    priceUSD: 7500,
    strengths: [
      'Free tier available plus affordable entry point for SMB ecommerce',
      '7 attribution models including Total Impact (blends MTA + post-purchase surveys)',
      'Moby AI agents for automated insights and cross-model comparisons',
      '50,000+ brands and 2,000+ agencies; deep Shopify/ecommerce integration',
    ],
    bestFor: 'E-commerce and DTC brands on Shopify wanting attribution, MMM, and AI-powered analytics in one affordable platform',
    hasIncrementality: false,
    offersMTA: true,
    offersMMM: true,
    mtaDetail: '7 attribution models including pixel-based and post-purchase surveys',
    mmmDetail: 'Marketing mix modeling (launched 2024–2025) with scenario planning',
  },
  {
    name: 'Measured',
    url: 'https://www.measured.com',
    category: 'both',
    founded: '2017',
    hq: 'New York, NY',
    audienceTags: ['Enterprise', 'CPG / Retail', 'E-commerce / DTC', 'Multi-National'],
    models: [
      'Incrementality Testing',
      'Causal MMM (test-calibrated)',
      'Media Plan Optimizer',
      'Triangulated Measurement',
    ],
    modelSupport: m(['mmm-suite', 'incrementality', 'scenario'], ['mta-suite']),
    priceTier: '$$$$',
    priceLabel: '$400K-$600K/yr for enterprise',
    priceUSD: 500000,
    strengths: [
      'Incrementality-first approach — MMM calibrated by real-world causal experiments',
      'Triangulated measurement combining incrementality + MMM + ad platform data',
      'Enterprise-grade with clients like Carter\'s, Chevron, Foot Locker, Intuit, Mars',
      'Media Plan Optimizer and cross-channel benchmarking against peer brands',
    ],
    bestFor: 'Enterprise brands with $10M+ in media spend needing causal, test-calibrated MMM and incrementality testing',
    hasIncrementality: true,
    offersMTA: false,
    offersMMM: true,
    mtaDetail: 'Leverages ad platform attribution data as one input to triangulation',
    mmmDetail: 'Incrementality-calibrated MMM with causal experimentation',
  },
  {
    name: 'AdBeacon',
    url: 'https://adbeacon.com',
    category: 'both',
    founded: '2021',
    hq: 'Unknown',
    audienceTags: ['E-commerce / DTC', 'Shopify', 'Performance Marketing'],
    models: [
      'First Touch',
      'Last Touch',
      'Linear',
      'Time Decay',
      'Position-Based',
      'Google Meridian MMM',
    ],
    modelSupport: m(['mta-suite', 'mmm-suite'], ['incrementality']),
    priceTier: '$',
    priceLabel: '$299/mo (~$3.6K/yr)',
    priceUSD: 3588,
    strengths: [
      'All features at one flat price — no paywalls or tiers',
      'Google Meridian MMM included in all plans',
      '15-minute Shopify setup with white-glove onboarding',
      'New vs returning customer reporting with LTV/RFM analysis',
    ],
    bestFor: 'E-commerce brands needing straightforward attribution with Google Meridian MMM at one flat price',
    hasIncrementality: true,
    offersMTA: true,
    offersMMM: true,
    mtaDetail: 'First-party multi-touch attribution with creative-level insights',
    mmmDetail: 'Google Meridian MMM included in all plans',
  },
  {
    name: 'Neustar (TransUnion)',
    url: 'https://www.transunion.com/solution/truaudience',
    category: 'both',
    founded: '1999',
    hq: 'Chicago, IL',
    audienceTags: ['Enterprise', 'Multi-National', 'CPG / Retail', 'Performance Marketing'],
    models: [
      'Marketing Mix Modeling',
      'Closed-Loop Attribution',
      'Testing & Experimentation',
      'Benchmark Studies',
    ],
    modelSupport: m(['mta-suite', 'mmm-suite', 'incrementality', 'scenario']),
    priceTier: '$$$$',
    priceLabel: 'Custom (Enterprise)',
    priceUSD: null,
    strengths: [
      'Identity-driven measurement powered by TransUnion identity graph',
      'Full MMM + closed-loop attribution + incrementality testing suite',
      'Privacy-first approach with deterministic identity resolution',
      'Forrester-validated 130% ROAS increase and 10x ROI on solution investment',
    ],
    bestFor: 'Large enterprises needing unified identity-driven marketing analytics combining MMM, MTA, and incrementality',
    hasIncrementality: true,
    offersMTA: true,
    offersMMM: true,
    mtaDetail: 'Closed-loop attribution powered by TransUnion identity graph',
    mmmDetail: 'Marketing mix modeling with scenario planning and benchmark studies',
  },
];
